# Generated by Django 3.2.8 on 2021-10-11 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name_plural': 'Transactionhistory'},
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transactiondate',
            field=models.DateTimeField(db_column='TransactionDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
