# Generated by Django 3.2.8 on 2021-10-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('adid', models.AutoField(db_column='adId', primary_key=True, serialize=False)),
                ('tournamentid', models.IntegerField(db_column='tournamentId')),
                ('adlocation', models.CharField(db_column='adLocation', max_length=45)),
                ('addescription', models.CharField(blank=True, db_column='adDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Advertisements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournamentid', models.AutoField(db_column='tournamentId', primary_key=True, serialize=False)),
                ('tournamentdate', models.DateTimeField(db_column='TournamentDate')),
                ('tournamnetsponsor', models.IntegerField(db_column='tournamnetSponsor')),
                ('tournamentprize', models.DecimalField(blank=True, db_column='tournamentPrize', decimal_places=2, max_digits=6, null=True)),
                ('tournamentholecount', models.IntegerField(blank=True, db_column='tournamentHoleCount', null=True)),
            ],
            options={
                'db_table': 'Tournaments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournamentparticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userId')),
                ('tournamentid', models.IntegerField(blank=True, db_column='tournamentId', null=True, unique=True)),
                ('userscore', models.IntegerField(blank=True, db_column='userScore', null=True)),
            ],
            options={
                'db_table': 'TournamentParticipants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('useremail', models.CharField(db_column='userEmail', max_length=320, unique=True)),
                ('userfirstname', models.CharField(db_column='userFirstName', max_length=45)),
                ('userlastname', models.CharField(blank=True, db_column='userLastName', max_length=45, null=True)),
                ('userpassword', models.CharField(db_column='userPassword', max_length=128)),
                ('useraccount', models.DecimalField(blank=True, db_column='userAccount', decimal_places=2, max_digits=6, null=True)),
                ('userrole', models.IntegerField(db_column='userRole')),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Advertisements',
        ),
        migrations.DeleteModel(
            name='Tournamentparticipants',
        ),
        migrations.DeleteModel(
            name='Tournaments',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'managed': False, 'verbose_name_plural': 'Transactionhistories'},
        ),
    ]
