# Generated by Django 3.2.8 on 2021-10-23 04:04

from django.db import migrations
import hashlib
import datetime

def create_users(apps, schema_editor):
    """
    Create two users with the following properties:
        - username: 'user1'
        - password: 'user1'
        - email: '
    """
    User = apps.get_model('backend', 'User')
    user_time_salt = "2021-10-22 22:14:36.000573"
    #user1 = User.objects.create_user(username='user1', userpassword='user1', useremail='', usersalt='')
    #user2 = User.objects.create_user(username='user2', password='user2', email='')

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_usersalt'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]

