# Generated by Django 3.2.8 on 2021-10-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211022_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usersalt',
        ),
    ]
