# Generated by Django 3.2.8 on 2021-11-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_database_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournamentactiveflag',
            field=models.BooleanField(db_column='tournamentActiveFlag', default=False),
        ),
    ]
