# Generated by Django 3.2.8 on 2021-10-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_database_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='transactionactiveflag',
            field=models.BooleanField(db_column='transactionActiveFlag', default=True),
        ),
    ]
