# Generated by Django 3.2.8 on 2021-10-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_usersalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usersalt',
            field=models.CharField(db_column='userSalt', max_length=128, null=True),
        ),
    ]
