# Generated by Django 3.0.3 on 2021-11-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_tournament_tournamentactiveflag'),
        ('backend', '0005_tournament_tournamentactiveflag'),
    ]

    operations = [
    ]
