-- MySQL Script generated by MySQL Workbench
-- Mon Oct  4 13:32:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Advertisements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Advertisements` (
  `adId` INT NOT NULL AUTO_INCREMENT,
  `tournamentId` INT NOT NULL,
  `adLocation` VARCHAR(45) NOT NULL,
  `adDescription` VARCHAR(500) NULL,
  PRIMARY KEY (`adId`),
  UNIQUE INDEX `adId_UNIQUE` (`adId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(45) NOT NULL,
  `itemDescription` VARCHAR(500) NULL,
  `itemPrice` DECIMAL(5,2) NULL,
  `TransactionHistory_transactionId` INT NOT NULL,
  UNIQUE INDEX `itemId_UNIQUE` (`itemId` ASC) VISIBLE,
  UNIQUE INDEX `itemName_UNIQUE` (`itemName` ASC) VISIBLE,
  PRIMARY KEY (`itemId`, `TransactionHistory_transactionId`),
  INDEX `fk_Menu_TransactionHistory_idx` (`TransactionHistory_transactionId` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_TransactionHistory`
    FOREIGN KEY (`TransactionHistory_transactionId`)
    REFERENCES `mydb`.`TransactionHistory` (`transactionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TournamentParticipants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TournamentParticipants` (
  `userId` INT NOT NULL,
  `tournamentId` INT NULL,
  `userScore` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tournaments` (
  `tournamentId` INT NOT NULL AUTO_INCREMENT,
  `TournamentDate` DATETIME NOT NULL,
  `tournamnetSponsor` INT NOT NULL,
  `tournamentPrize` DECIMAL(6,2) NULL,
  `tournamentHoleCount` INT NULL,
  `TournamentParticipants_userId` INT NOT NULL,
  `Advertisements_adId` INT NOT NULL,
  UNIQUE INDEX `tournamentId_UNIQUE` (`tournamentId` ASC) VISIBLE,
  PRIMARY KEY (`tournamentId`, `TournamentParticipants_userId`, `Advertisements_adId`),
  INDEX `fk_Tournaments_TournamentParticipants1_idx` (`TournamentParticipants_userId` ASC) VISIBLE,
  INDEX `fk_Tournaments_Advertisements1_idx` (`Advertisements_adId` ASC) VISIBLE,
  CONSTRAINT `fk_Tournaments_TournamentParticipants1`
    FOREIGN KEY (`TournamentParticipants_userId`)
    REFERENCES `mydb`.`TournamentParticipants` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tournaments_Advertisements1`
    FOREIGN KEY (`Advertisements_adId`)
    REFERENCES `mydb`.`Advertisements` (`adId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransactionHistory` (
  `transactionId` INT NOT NULL AUTO_INCREMENT,
  `transactionPrice` DECIMAL(5,2) NOT NULL,
  `transactionBuyer` INT NOT NULL,
  `transactionDrinkMeister` INT NULL,
  UNIQUE INDEX `transactionId_UNIQUE` (`transactionId` ASC) VISIBLE,
  PRIMARY KEY (`transactionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userEmail` VARCHAR(320) NOT NULL,
  `userFirstName` VARCHAR(45) NOT NULL,
  `userLastName` VARCHAR(45) NULL,
  `userPassword` VARCHAR(128) NOT NULL,
  `userAccount` DECIMAL(6,2) NULL,
  `userRole` INT NOT NULL,
  `TransactionHistory_transactionId` INT NOT NULL,
  `TournamentParticipants_userId` INT NOT NULL,
  UNIQUE INDEX `idUsers_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC) VISIBLE,
  PRIMARY KEY (`userId`, `TransactionHistory_transactionId`, `TournamentParticipants_userId`),
  INDEX `fk_Users_TransactionHistory1_idx` (`TransactionHistory_transactionId` ASC) VISIBLE,
  INDEX `fk_Users_TournamentParticipants1_idx` (`TournamentParticipants_userId` ASC) VISIBLE,
  CONSTRAINT `fk_Users_TransactionHistory1`
    FOREIGN KEY (`TransactionHistory_transactionId`)
    REFERENCES `mydb`.`TransactionHistory` (`transactionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_TournamentParticipants1`
    FOREIGN KEY (`TournamentParticipants_userId`)
    REFERENCES `mydb`.`TournamentParticipants` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
