-- MySQL Script generated by MySQL Workbench
-- Thu Oct  7 13:13:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Dimension4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Dimension4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Dimension4` DEFAULT CHARACTER SET utf8 ;
USE `Dimension4` ;

-- -----------------------------------------------------
-- Table `Dimension4`.`Advertisements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dimension4`.`Advertisements` (
  `adId` INT NOT NULL AUTO_INCREMENT,
  `tournamentId` INT NOT NULL,
  `adLocation` VARCHAR(45) NOT NULL,
  `adDescription` VARCHAR(500) NULL,
  PRIMARY KEY (`adId`),
  UNIQUE INDEX `adId_UNIQUE` (`adId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dimension4`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dimension4`.`Menu` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(45) NOT NULL,
  `itemDescription` VARCHAR(500) NULL,
  `itemPrice` DECIMAL(5,2) NULL,
  UNIQUE INDEX `itemId_UNIQUE` (`itemId` ASC) VISIBLE,
  UNIQUE INDEX `itemName_UNIQUE` (`itemName` ASC) VISIBLE,
  PRIMARY KEY (`itemId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dimension4`.`TournamentParticipants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dimension4`.`TournamentParticipants` (
  `userId` INT NOT NULL,
  `tournamentId` INT NULL,
  `userScore` INT NULL,
  UNIQUE INDEX `tournamentId_UNIQUE` (`tournamentId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dimension4`.`Tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dimension4`.`Tournaments` (
  `tournamentId` INT NOT NULL AUTO_INCREMENT,
  `TournamentDate` DATETIME NOT NULL,
  `tournamnetSponsor` INT NOT NULL,
  `tournamentPrize` DECIMAL(6,2) NULL,
  `tournamentHoleCount` INT NULL,
  UNIQUE INDEX `tournamentId_UNIQUE` (`tournamentId` ASC) VISIBLE,
  PRIMARY KEY (`tournamentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dimension4`.`TransactionHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dimension4`.`TransactionHistory` (
  `transactionId` INT NOT NULL AUTO_INCREMENT,
  `transactionPrice` DECIMAL(5,2) NOT NULL,
  `transactionBuyer` INT NOT NULL,
  `transactionDrinkMeister` INT NULL,
  UNIQUE INDEX `transactionId_UNIQUE` (`transactionId` ASC) VISIBLE,
  PRIMARY KEY (`transactionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dimension4`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dimension4`.`Users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userEmail` VARCHAR(320) NOT NULL,
  `userFirstName` VARCHAR(45) NOT NULL,
  `userLastName` VARCHAR(45) NULL,
  `userPassword` VARCHAR(128) NOT NULL,
  `userAccount` DECIMAL(6,2) NULL,
  `userRole` INT NOT NULL,
  UNIQUE INDEX `idUsers_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC) VISIBLE,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
